package com.citytuike.model;

public class TpAdPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.position_id
     *
     * @mbggenerated
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.position_name
     *
     * @mbggenerated
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.ad_width
     *
     * @mbggenerated
     */
    private Integer adWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.ad_height
     *
     * @mbggenerated
     */
    private Integer adHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.position_desc
     *
     * @mbggenerated
     */
    private String positionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.is_open
     *
     * @mbggenerated
     */
    private Integer isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.region_id
     *
     * @mbggenerated
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_position.position_style
     *
     * @mbggenerated
     */
    private String positionStyle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.position_id
     *
     * @return the value of tp_ad_position.position_id
     *
     * @mbggenerated
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.position_id
     *
     * @param positionId the value for tp_ad_position.position_id
     *
     * @mbggenerated
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.position_name
     *
     * @return the value of tp_ad_position.position_name
     *
     * @mbggenerated
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.position_name
     *
     * @param positionName the value for tp_ad_position.position_name
     *
     * @mbggenerated
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName == null ? null : positionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.ad_width
     *
     * @return the value of tp_ad_position.ad_width
     *
     * @mbggenerated
     */
    public Integer getAdWidth() {
        return adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.ad_width
     *
     * @param adWidth the value for tp_ad_position.ad_width
     *
     * @mbggenerated
     */
    public void setAdWidth(Integer adWidth) {
        this.adWidth = adWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.ad_height
     *
     * @return the value of tp_ad_position.ad_height
     *
     * @mbggenerated
     */
    public Integer getAdHeight() {
        return adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.ad_height
     *
     * @param adHeight the value for tp_ad_position.ad_height
     *
     * @mbggenerated
     */
    public void setAdHeight(Integer adHeight) {
        this.adHeight = adHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.position_desc
     *
     * @return the value of tp_ad_position.position_desc
     *
     * @mbggenerated
     */
    public String getPositionDesc() {
        return positionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.position_desc
     *
     * @param positionDesc the value for tp_ad_position.position_desc
     *
     * @mbggenerated
     */
    public void setPositionDesc(String positionDesc) {
        this.positionDesc = positionDesc == null ? null : positionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.is_open
     *
     * @return the value of tp_ad_position.is_open
     *
     * @mbggenerated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.is_open
     *
     * @param isOpen the value for tp_ad_position.is_open
     *
     * @mbggenerated
     */
    public void setIsOpen(Integer isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.region_id
     *
     * @return the value of tp_ad_position.region_id
     *
     * @mbggenerated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.region_id
     *
     * @param regionId the value for tp_ad_position.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.address
     *
     * @return the value of tp_ad_position.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.address
     *
     * @param address the value for tp_ad_position.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.device_id
     *
     * @return the value of tp_ad_position.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.device_id
     *
     * @param deviceId the value for tp_ad_position.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_position.position_style
     *
     * @return the value of tp_ad_position.position_style
     *
     * @mbggenerated
     */
    public String getPositionStyle() {
        return positionStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_position.position_style
     *
     * @param positionStyle the value for tp_ad_position.position_style
     *
     * @mbggenerated
     */
    public void setPositionStyle(String positionStyle) {
        this.positionStyle = positionStyle == null ? null : positionStyle.trim();
    }
}