package com.citytuike.model;

import java.util.Date;

public class TpAdLaunch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.launch_start_date
     *
     * @mbggenerated
     */
    private Date launchStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.launch_end_date
     *
     * @mbggenerated
     */
    private Date launchEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.apply_id
     *
     * @mbggenerated
     */
    private Integer applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.obj_type
     *
     * @mbggenerated
     */
    private Integer objType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.obj_id
     *
     * @mbggenerated
     */
    private Integer objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_ad_launch.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.id
     *
     * @return the value of tp_ad_launch.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.id
     *
     * @param id the value for tp_ad_launch.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.launch_start_date
     *
     * @return the value of tp_ad_launch.launch_start_date
     *
     * @mbggenerated
     */
    public Date getLaunchStartDate() {
        return launchStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.launch_start_date
     *
     * @param launchStartDate the value for tp_ad_launch.launch_start_date
     *
     * @mbggenerated
     */
    public void setLaunchStartDate(Date launchStartDate) {
        this.launchStartDate = launchStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.launch_end_date
     *
     * @return the value of tp_ad_launch.launch_end_date
     *
     * @mbggenerated
     */
    public Date getLaunchEndDate() {
        return launchEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.launch_end_date
     *
     * @param launchEndDate the value for tp_ad_launch.launch_end_date
     *
     * @mbggenerated
     */
    public void setLaunchEndDate(Date launchEndDate) {
        this.launchEndDate = launchEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.apply_id
     *
     * @return the value of tp_ad_launch.apply_id
     *
     * @mbggenerated
     */
    public Integer getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.apply_id
     *
     * @param applyId the value for tp_ad_launch.apply_id
     *
     * @mbggenerated
     */
    public void setApplyId(Integer applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.obj_type
     *
     * @return the value of tp_ad_launch.obj_type
     *
     * @mbggenerated
     */
    public Integer getObjType() {
        return objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.obj_type
     *
     * @param objType the value for tp_ad_launch.obj_type
     *
     * @mbggenerated
     */
    public void setObjType(Integer objType) {
        this.objType = objType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.obj_id
     *
     * @return the value of tp_ad_launch.obj_id
     *
     * @mbggenerated
     */
    public Integer getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.obj_id
     *
     * @param objId the value for tp_ad_launch.obj_id
     *
     * @mbggenerated
     */
    public void setObjId(Integer objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.created_at
     *
     * @return the value of tp_ad_launch.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.created_at
     *
     * @param createdAt the value for tp_ad_launch.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.updated_at
     *
     * @return the value of tp_ad_launch.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.updated_at
     *
     * @param updatedAt the value for tp_ad_launch.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.user_id
     *
     * @return the value of tp_ad_launch.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.user_id
     *
     * @param userId the value for tp_ad_launch.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_ad_launch.status
     *
     * @return the value of tp_ad_launch.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_ad_launch.status
     *
     * @param status the value for tp_ad_launch.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}