package com.citytuike.model;

public class TpArticleCat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_id
     *
     * @mbggenerated
     */
    private Integer catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_name
     *
     * @mbggenerated
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_type
     *
     * @mbggenerated
     */
    private Integer catType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.show_in_nav
     *
     * @mbggenerated
     */
    private Integer showInNav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_desc
     *
     * @mbggenerated
     */
    private String catDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_alias
     *
     * @mbggenerated
     */
    private String catAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_article_cat.cat_icon
     *
     * @mbggenerated
     */
    private String catIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_id
     *
     * @return the value of tp_article_cat.cat_id
     *
     * @mbggenerated
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_id
     *
     * @param catId the value for tp_article_cat.cat_id
     *
     * @mbggenerated
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_name
     *
     * @return the value of tp_article_cat.cat_name
     *
     * @mbggenerated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_name
     *
     * @param catName the value for tp_article_cat.cat_name
     *
     * @mbggenerated
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_type
     *
     * @return the value of tp_article_cat.cat_type
     *
     * @mbggenerated
     */
    public Integer getCatType() {
        return catType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_type
     *
     * @param catType the value for tp_article_cat.cat_type
     *
     * @mbggenerated
     */
    public void setCatType(Integer catType) {
        this.catType = catType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.parent_id
     *
     * @return the value of tp_article_cat.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.parent_id
     *
     * @param parentId the value for tp_article_cat.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.show_in_nav
     *
     * @return the value of tp_article_cat.show_in_nav
     *
     * @mbggenerated
     */
    public Integer getShowInNav() {
        return showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.show_in_nav
     *
     * @param showInNav the value for tp_article_cat.show_in_nav
     *
     * @mbggenerated
     */
    public void setShowInNav(Integer showInNav) {
        this.showInNav = showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.sort_order
     *
     * @return the value of tp_article_cat.sort_order
     *
     * @mbggenerated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.sort_order
     *
     * @param sortOrder the value for tp_article_cat.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_desc
     *
     * @return the value of tp_article_cat.cat_desc
     *
     * @mbggenerated
     */
    public String getCatDesc() {
        return catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_desc
     *
     * @param catDesc the value for tp_article_cat.cat_desc
     *
     * @mbggenerated
     */
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc == null ? null : catDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.keywords
     *
     * @return the value of tp_article_cat.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.keywords
     *
     * @param keywords the value for tp_article_cat.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_alias
     *
     * @return the value of tp_article_cat.cat_alias
     *
     * @mbggenerated
     */
    public String getCatAlias() {
        return catAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_alias
     *
     * @param catAlias the value for tp_article_cat.cat_alias
     *
     * @mbggenerated
     */
    public void setCatAlias(String catAlias) {
        this.catAlias = catAlias == null ? null : catAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_article_cat.cat_icon
     *
     * @return the value of tp_article_cat.cat_icon
     *
     * @mbggenerated
     */
    public String getCatIcon() {
        return catIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_article_cat.cat_icon
     *
     * @param catIcon the value for tp_article_cat.cat_icon
     *
     * @mbggenerated
     */
    public void setCatIcon(String catIcon) {
        this.catIcon = catIcon == null ? null : catIcon.trim();
    }
}