package com.citytuike.model;

import java.math.BigDecimal;
import java.util.Date;

public class TpBusinessDiscount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.business_address
     *
     * @mbggenerated
     */
    private String businessAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.price
     *
     * @mbggenerated
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.discount_price
     *
     * @mbggenerated
     */
    private double discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.valid_date
     *
     * @mbggenerated
     */
    private Integer validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.launch_address
     *
     * @mbggenerated
     */
    private String launchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.launch_id
     *
     * @mbggenerated
     */
    private String launchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.launch_date_start
     *
     * @mbggenerated
     */
    private Integer launchDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.launch_date_end
     *
     * @mbggenerated
     */
    private Integer launchDateEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.nums
     *
     * @mbggenerated
     */
    private Integer nums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_discount.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.id
     *
     * @return the value of tp_business_discount.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.id
     *
     * @param id the value for tp_business_discount.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.business_id
     *
     * @return the value of tp_business_discount.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.business_id
     *
     * @param businessId the value for tp_business_discount.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.business_name
     *
     * @return the value of tp_business_discount.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.business_name
     *
     * @param businessName the value for tp_business_discount.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.business_address
     *
     * @return the value of tp_business_discount.business_address
     *
     * @mbggenerated
     */
    public String getBusinessAddress() {
        return businessAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.business_address
     *
     * @param businessAddress the value for tp_business_discount.business_address
     *
     * @mbggenerated
     */
    public void setBusinessAddress(String businessAddress) {
        this.businessAddress = businessAddress == null ? null : businessAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.price
     *
     * @return the value of tp_business_discount.price
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.price
     *
     * @param price the value for tp_business_discount.price
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.discount_price
     *
     * @return the value of tp_business_discount.discount_price
     *
     * @mbggenerated
     */
    public double getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.discount_price
     *
     * @param discountPrice the value for tp_business_discount.discount_price
     *
     * @mbggenerated
     */
    public void setDiscountPrice(double discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.valid_date
     *
     * @return the value of tp_business_discount.valid_date
     *
     * @mbggenerated
     */
    public Integer getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.valid_date
     *
     * @param validDate the value for tp_business_discount.valid_date
     *
     * @mbggenerated
     */
    public void setValidDate(Integer validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.launch_address
     *
     * @return the value of tp_business_discount.launch_address
     *
     * @mbggenerated
     */
    public String getLaunchAddress() {
        return launchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.launch_address
     *
     * @param launchAddress the value for tp_business_discount.launch_address
     *
     * @mbggenerated
     */
    public void setLaunchAddress(String launchAddress) {
        this.launchAddress = launchAddress == null ? null : launchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.launch_id
     *
     * @return the value of tp_business_discount.launch_id
     *
     * @mbggenerated
     */
    public String getLaunchId() {
        return launchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.launch_id
     *
     * @param launchId the value for tp_business_discount.launch_id
     *
     * @mbggenerated
     */
    public void setLaunchId(String launchId) {
        this.launchId = launchId == null ? null : launchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.launch_date_start
     *
     * @return the value of tp_business_discount.launch_date_start
     *
     * @mbggenerated
     */
    public Integer getLaunchDateStart() {
        return launchDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.launch_date_start
     *
     * @param launchDateStart the value for tp_business_discount.launch_date_start
     *
     * @mbggenerated
     */
    public void setLaunchDateStart(Integer launchDateStart) {
        this.launchDateStart = launchDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.launch_date_end
     *
     * @return the value of tp_business_discount.launch_date_end
     *
     * @mbggenerated
     */
    public Integer getLaunchDateEnd() {
        return launchDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.launch_date_end
     *
     * @param launchDateEnd the value for tp_business_discount.launch_date_end
     *
     * @mbggenerated
     */
    public void setLaunchDateEnd(Integer launchDateEnd) {
        this.launchDateEnd = launchDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.nums
     *
     * @return the value of tp_business_discount.nums
     *
     * @mbggenerated
     */
    public Integer getNums() {
        return nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.nums
     *
     * @param nums the value for tp_business_discount.nums
     *
     * @mbggenerated
     */
    public void setNums(Integer nums) {
        this.nums = nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.add_time
     *
     * @return the value of tp_business_discount.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.add_time
     *
     * @param addTime the value for tp_business_discount.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.image
     *
     * @return the value of tp_business_discount.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.image
     *
     * @param image the value for tp_business_discount.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_discount.status
     *
     * @return the value of tp_business_discount.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_discount.status
     *
     * @param status the value for tp_business_discount.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}