package com.citytuike.model;

public class TpBusinessUseCash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.cash_id
     * 现金券id
     * @mbggenerated
     */
    private Integer cashId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.number
     * 生成编号
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.business_id
     * 商户id
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.flag
     * 有没使用过期, 0未使用1已使用2已过期
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.add_time
     * 日期
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.codes
     * 激活码
     * @mbggenerated
     */
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.user_use_id
     * 发送给哪个用户
     * @mbggenerated
     */
    private Integer userUseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.use_status
     * 有没过期 1未过期2已过期
     * @mbggenerated
     */
    private Integer useStatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_use_cash.use_status
     * 1现金券2折扣券
     * @mbggenerated
     */
    private Integer type;

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.id
     *
     * @return the value of tp_business_use_cash.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.id
     *
     * @param id the value for tp_business_use_cash.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.user_id
     *
     * @return the value of tp_business_use_cash.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.user_id
     *
     * @param userId the value for tp_business_use_cash.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.cash_id
     *
     * @return the value of tp_business_use_cash.cash_id
     *
     * @mbggenerated
     */
    public Integer getCashId() {
        return cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.cash_id
     *
     * @param cashId the value for tp_business_use_cash.cash_id
     *
     * @mbggenerated
     */
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.number
     *
     * @return the value of tp_business_use_cash.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.number
     *
     * @param number the value for tp_business_use_cash.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.business_id
     *
     * @return the value of tp_business_use_cash.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.business_id
     *
     * @param businessId the value for tp_business_use_cash.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.flag
     *
     * @return the value of tp_business_use_cash.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.flag
     *
     * @param flag the value for tp_business_use_cash.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.add_time
     *
     * @return the value of tp_business_use_cash.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.add_time
     *
     * @param addTime the value for tp_business_use_cash.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.codes
     *
     * @return the value of tp_business_use_cash.codes
     *
     * @mbggenerated
     */
    public String getCodes() {
        return codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.codes
     *
     * @param codes the value for tp_business_use_cash.codes
     *
     * @mbggenerated
     */
    public void setCodes(String codes) {
        this.codes = codes == null ? null : codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.user_use_id
     *
     * @return the value of tp_business_use_cash.user_use_id
     *
     * @mbggenerated
     */
    public Integer getUserUseId() {
        return userUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.user_use_id
     *
     * @param userUseId the value for tp_business_use_cash.user_use_id
     *
     * @mbggenerated
     */
    public void setUserUseId(Integer userUseId) {
        this.userUseId = userUseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_use_cash.use_status
     *
     * @return the value of tp_business_use_cash.use_status
     *
     * @mbggenerated
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_use_cash.use_status
     *
     * @param useStatus the value for tp_business_use_cash.use_status
     *
     * @mbggenerated
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }
}