package com.citytuike.model;

public class TpBusinessImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_images.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_images.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_images.img_sort
     *
     * @mbggenerated
     */
    private Integer imgSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_images.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_images.id
     *
     * @return the value of tp_business_images.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_images.id
     *
     * @param id the value for tp_business_images.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_images.business_id
     *
     * @return the value of tp_business_images.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_images.business_id
     *
     * @param businessId the value for tp_business_images.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_images.img_sort
     *
     * @return the value of tp_business_images.img_sort
     *
     * @mbggenerated
     */
    public Integer getImgSort() {
        return imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_images.img_sort
     *
     * @param imgSort the value for tp_business_images.img_sort
     *
     * @mbggenerated
     */
    public void setImgSort(Integer imgSort) {
        this.imgSort = imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_images.image
     *
     * @return the value of tp_business_images.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_images.image
     *
     * @param image the value for tp_business_images.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}