package com.citytuike.model;

public class TpBusinessTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_tag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_tag.comment_id
     *
     * @mbggenerated
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_tag.comment_tag
     *
     * @mbggenerated
     */
    private String commentTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_tag.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_tag.id
     *
     * @return the value of tp_business_tag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_tag.id
     *
     * @param id the value for tp_business_tag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_tag.comment_id
     *
     * @return the value of tp_business_tag.comment_id
     *
     * @mbggenerated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_tag.comment_id
     *
     * @param commentId the value for tp_business_tag.comment_id
     *
     * @mbggenerated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_tag.comment_tag
     *
     * @return the value of tp_business_tag.comment_tag
     *
     * @mbggenerated
     */
    public String getCommentTag() {
        return commentTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_tag.comment_tag
     *
     * @param commentTag the value for tp_business_tag.comment_tag
     *
     * @mbggenerated
     */
    public void setCommentTag(String commentTag) {
        this.commentTag = commentTag == null ? null : commentTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_tag.add_time
     *
     * @return the value of tp_business_tag.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_tag.add_time
     *
     * @param addTime the value for tp_business_tag.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }
}