package com.citytuike.model;

import java.math.BigDecimal;

public class TpBusinessSave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.cash_id
     *
     * @mbggenerated
     */
    private Integer cashId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.baozhengjin
     *
     * @mbggenerated
     */
    private double baozhengjin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.order_sn
     *
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.face_id
     *
     * @mbggenerated
     */
    private Integer faceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_save.current_time
     *
     * @mbggenerated
     */
    private Integer currentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.id
     *
     * @return the value of tp_business_save.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.id
     *
     * @param id the value for tp_business_save.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.business_id
     *
     * @return the value of tp_business_save.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.business_id
     *
     * @param businessId the value for tp_business_save.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.cash_id
     *
     * @return the value of tp_business_save.cash_id
     *
     * @mbggenerated
     */
    public Integer getCashId() {
        return cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.cash_id
     *
     * @param cashId the value for tp_business_save.cash_id
     *
     * @mbggenerated
     */
    public void setCashId(Integer cashId) {
        this.cashId = cashId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.baozhengjin
     *
     * @return the value of tp_business_save.baozhengjin
     *
     * @mbggenerated
     */
    public double getBaozhengjin() {
        return baozhengjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.baozhengjin
     *
     * @param baozhengjin the value for tp_business_save.baozhengjin
     *
     * @mbggenerated
     */
    public void setBaozhengjin(double baozhengjin) {
        this.baozhengjin = baozhengjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.add_time
     *
     * @return the value of tp_business_save.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.add_time
     *
     * @param addTime the value for tp_business_save.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.order_sn
     *
     * @return the value of tp_business_save.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.order_sn
     *
     * @param orderSn the value for tp_business_save.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.flag
     *
     * @return the value of tp_business_save.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.flag
     *
     * @param flag the value for tp_business_save.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.face_id
     *
     * @return the value of tp_business_save.face_id
     *
     * @mbggenerated
     */
    public Integer getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.face_id
     *
     * @param faceId the value for tp_business_save.face_id
     *
     * @mbggenerated
     */
    public void setFaceId(Integer faceId) {
        this.faceId = faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.create_time
     *
     * @return the value of tp_business_save.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.create_time
     *
     * @param createTime the value for tp_business_save.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_save.current_time
     *
     * @return the value of tp_business_save.current_time
     *
     * @mbggenerated
     */
    public Integer getCurrentTime() {
        return currentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_save.current_time
     *
     * @param currentTime the value for tp_business_save.current_time
     *
     * @mbggenerated
     */
    public void setCurrentTime(Integer currentTime) {
        this.currentTime = currentTime;
    }
}