package com.citytuike.model;

import java.math.BigDecimal;

public class TpBusinessCash {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.skin
     * 皮肤颜色
     * @mbggenerated
     */
    private String skin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.business_id
     * 商户id
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.business_name
     * 商户名
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.price
     * 现金券金额
     * @mbggenerated
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.fullsub_price
     * 满减金额
     * @mbggenerated
     */
    private double fullsubPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.price_date
     * 使用日期
     * @mbggenerated
     */
    private Integer priceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.use_flag
     * 限制地区
     * @mbggenerated
     */
    private String useFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.launch_address
     * 投放地区
     * @mbggenerated
     */
    private String launchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.launch_id
     * 投放地区id
     * @mbggenerated
     */
    private Integer launchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.launch_date_start
     * 投放时间段
     * @mbggenerated
     */
    private Integer launchDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.nums
     * 制作数量
     * @mbggenerated
     */
    private Integer nums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.launch_date_end
     *
     * @mbggenerated
     */
    private Integer launchDateEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.baozhengjin
     *
     * @mbggenerated
     */
    private double baozhengjin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.thaw_mess
     * 解冻理由
     * @mbggenerated
     */
    private String thawMess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.thaw_flag
     * 0未解冻1已解冻2解冻中
     * @mbggenerated
     */
    private int thawFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash.jie_time
     *
     * @mbggenerated
     */
    private Integer jieTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.id
     *
     * @return the value of tp_business_cash.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.id
     *
     * @param id the value for tp_business_cash.id.0
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.skin
     *
     * @return the value of tp_business_cash.skin
     *
     * @mbggenerated
     */
    public String getSkin() {
        return skin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.skin
     *
     * @param skin the value for tp_business_cash.skin
     *
     * @mbggenerated
     */
    public void setSkin(String skin) {
        this.skin = skin == null ? null : skin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.business_id
     *
     * @return the value of tp_business_cash.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.business_id
     *
     * @param businessId the value for tp_business_cash.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.business_name
     *
     * @return the value of tp_business_cash.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.business_name
     *
     * @param businessName the value for tp_business_cash.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.price
     *
     * @return the value of tp_business_cash.price
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.price
     *
     * @param price the value for tp_business_cash.price
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.fullsub_price
     *
     * @return the value of tp_business_cash.fullsub_price
     *
     * @mbggenerated
     */
    public double getFullsubPrice() {
        return fullsubPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.fullsub_price
     *
     * @param fullsubPrice the value for tp_business_cash.fullsub_price
     *
     * @mbggenerated
     */
    public void setFullsubPrice(double fullsubPrice) {
        this.fullsubPrice = fullsubPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.price_date
     *
     * @return the value of tp_business_cash.price_date
     *
     * @mbggenerated
     */
    public Integer getPriceDate() {
        return priceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.price_date
     *
     * @param priceDate the value for tp_business_cash.price_date
     *
     * @mbggenerated
     */
    public void setPriceDate(Integer priceDate) {
        this.priceDate = priceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.use_flag
     *
     * @return the value of tp_business_cash.use_flag
     *
     * @mbggenerated
     */
    public String getUseFlag() {
        return useFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.use_flag
     *
     * @param useFlag the value for tp_business_cash.use_flag
     *
     * @mbggenerated
     */
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag == null ? null : useFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.launch_address
     *
     * @return the value of tp_business_cash.launch_address
     *
     * @mbggenerated
     */
    public String getLaunchAddress() {
        return launchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.launch_address
     *
     * @param launchAddress the value for tp_business_cash.launch_address
     *
     * @mbggenerated
     */
    public void setLaunchAddress(String launchAddress) {
        this.launchAddress = launchAddress == null ? null : launchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.launch_id
     *
     * @return the value of tp_business_cash.launch_id
     *
     * @mbggenerated
     */
    public Integer getLaunchId() {
        return launchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.launch_id
     *
     * @param launchId the value for tp_business_cash.launch_id
     *
     * @mbggenerated
     */
    public void setLaunchId(Integer launchId) {
        this.launchId = launchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.launch_date_start
     *
     * @return the value of tp_business_cash.launch_date_start
     *
     * @mbggenerated
     */
    public Integer getLaunchDateStart() {
        return launchDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.launch_date_start
     *
     * @param launchDateStart the value for tp_business_cash.launch_date_start
     *
     * @mbggenerated
     */
    public void setLaunchDateStart(Integer launchDateStart) {
        this.launchDateStart = launchDateStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.nums
     *
     * @return the value of tp_business_cash.nums
     *
     * @mbggenerated
     */
    public Integer getNums() {
        return nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.nums
     *
     * @param nums the value for tp_business_cash.nums
     *
     * @mbggenerated
     */
    public void setNums(Integer nums) {
        this.nums = nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.launch_date_end
     *
     * @return the value of tp_business_cash.launch_date_end
     *
     * @mbggenerated
     */
    public Integer getLaunchDateEnd() {
        return launchDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.launch_date_end
     *
     * @param launchDateEnd the value for tp_business_cash.launch_date_end
     *
     * @mbggenerated
     */
    public void setLaunchDateEnd(Integer launchDateEnd) {
        this.launchDateEnd = launchDateEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.baozhengjin
     *
     * @return the value of tp_business_cash.baozhengjin
     *
     * @mbggenerated
     */
    public double getBaozhengjin() {
        return baozhengjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.baozhengjin
     *
     * @param baozhengjin the value for tp_business_cash.baozhengjin
     *
     * @mbggenerated
     */
    public void setBaozhengjin(double baozhengjin) {
        this.baozhengjin = baozhengjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.thaw_mess
     *
     * @return the value of tp_business_cash.thaw_mess
     *
     * @mbggenerated
     */
    public String getThawMess() {
        return thawMess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.thaw_mess
     *
     * @param thawMess the value for tp_business_cash.thaw_mess
     *
     * @mbggenerated
     */
    public void setThawMess(String thawMess) {
        this.thawMess = thawMess == null ? null : thawMess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.thaw_flag
     *
     * @return the value of tp_business_cash.thaw_flag
     *
     * @mbggenerated
     */
    public int getThawFlag() {
        return thawFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.thaw_flag
     *
     * @param thawFlag the value for tp_business_cash.thaw_flag
     *
     * @mbggenerated
     */
    public void setThawFlag(int thawFlag) {
        this.thawFlag = thawFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash.jie_time
     *
     * @return the value of tp_business_cash.jie_time
     *
     * @mbggenerated
     */
    public Integer getJieTime() {
        return jieTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash.jie_time
     *
     * @param jieTime the value for tp_business_cash.jie_time
     *
     * @mbggenerated
     */
    public void setJieTime(Integer jieTime) {
        this.jieTime = jieTime;
    }
}