package com.citytuike.model;

import java.math.BigDecimal;

public class TpBusinessOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.order_sn
     * 订单号
     * @mbggenerated
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.user_id
     * 用户id
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.pay_status
     * 支付状态 0待支付1已支付
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.flag
     * 与商家店铺关联1为该订单已关联2为未关联
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.business_id
     * 商家店铺名id
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.pay_time
     * 支付时间
     * @mbggenerated
     */
    private Integer payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.total_amount
     *
     * @mbggenerated
     */
    private double totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.pay_code
     *
     * @mbggenerated
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.pay_name
     *
     * @mbggenerated
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.goods_price
     *
     * @mbggenerated
     */
    private double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.order_amount
     *
     * @mbggenerated
     */
    private double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.order_status
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_order.face_id
     *
     * @mbggenerated
     */
    private Integer faceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.id
     *
     * @return the value of tp_business_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.id
     *
     * @param id the value for tp_business_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.order_sn
     *
     * @return the value of tp_business_order.order_sn
     *
     * @mbggenerated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.order_sn
     *
     * @param orderSn the value for tp_business_order.order_sn
     *
     * @mbggenerated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.user_id
     *
     * @return the value of tp_business_order.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.user_id
     *
     * @param userId the value for tp_business_order.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.pay_status
     *
     * @return the value of tp_business_order.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.pay_status
     *
     * @param payStatus the value for tp_business_order.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.flag
     *
     * @return the value of tp_business_order.flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.flag
     *
     * @param flag the value for tp_business_order.flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.business_id
     *
     * @return the value of tp_business_order.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.business_id
     *
     * @param businessId the value for tp_business_order.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.add_time
     *
     * @return the value of tp_business_order.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.add_time
     *
     * @param addTime the value for tp_business_order.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.pay_time
     *
     * @return the value of tp_business_order.pay_time
     *
     * @mbggenerated
     */
    public Integer getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.pay_time
     *
     * @param payTime the value for tp_business_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Integer payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.total_amount
     *
     * @return the value of tp_business_order.total_amount
     *
     * @mbggenerated
     */
    public double getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.total_amount
     *
     * @param totalAmount the value for tp_business_order.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.pay_code
     *
     * @return the value of tp_business_order.pay_code
     *
     * @mbggenerated
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.pay_code
     *
     * @param payCode the value for tp_business_order.pay_code
     *
     * @mbggenerated
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.pay_name
     *
     * @return the value of tp_business_order.pay_name
     *
     * @mbggenerated
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.pay_name
     *
     * @param payName the value for tp_business_order.pay_name
     *
     * @mbggenerated
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.goods_price
     *
     * @return the value of tp_business_order.goods_price
     *
     * @mbggenerated
     */
    public double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.goods_price
     *
     * @param goodsPrice the value for tp_business_order.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.order_amount
     *
     * @return the value of tp_business_order.order_amount
     *
     * @mbggenerated
     */
    public double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.order_amount
     *
     * @param orderAmount the value for tp_business_order.order_amount
     *
     * @mbggenerated
     */
    public void setOrderAmount(double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.order_status
     *
     * @return the value of tp_business_order.order_status
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.order_status
     *
     * @param orderStatus the value for tp_business_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_order.face_id
     *
     * @return the value of tp_business_order.face_id
     *
     * @mbggenerated
     */
    public Integer getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_order.face_id
     *
     * @param faceId the value for tp_business_order.face_id
     *
     * @mbggenerated
     */
    public void setFaceId(Integer faceId) {
        this.faceId = faceId;
    }
}