package com.citytuike.model;

public class TpBusinessComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.business_id
     * 关联商家id
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.stars
     * 星星数量
     * @mbggenerated
     */
    private Integer stars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.parent_id
     * 父id
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.tag
     *
     * @mbggenerated
     */
    private String tag;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.message
     * 评论内容
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.image_desc
     * 评论图片排序与图片逗号分开，图片分隔符
     * @mbggenerated
     */
    private String imageDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_comment.reply_mess
     * 回复内容
     * @mbggenerated
     */
    private String replyMess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.message
     *
     * @return the value of tp_business_comment.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.message
     *
     * @param message the value for tp_business_comment.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.image_desc
     *
     * @return the value of tp_business_comment.image_desc
     *
     * @mbggenerated
     */
    public String getImageDesc() {
        return imageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.image_desc
     *
     * @param imageDesc the value for tp_business_comment.image_desc
     *
     * @mbggenerated
     */
    public void setImageDesc(String imageDesc) {
        this.imageDesc = imageDesc == null ? null : imageDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.reply_mess
     *
     * @return the value of tp_business_comment.reply_mess
     *
     * @mbggenerated
     */
    public String getReplyMess() {
        return replyMess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.reply_mess
     *
     * @param replyMess the value for tp_business_comment.reply_mess
     *
     * @mbggenerated
     */
    public void setReplyMess(String replyMess) {
        this.replyMess = replyMess == null ? null : replyMess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.id
     *
     * @return the value of tp_business_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.id
     *
     * @param id the value for tp_business_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.business_id
     *
     * @return the value of tp_business_comment.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.business_id
     *
     * @param businessId the value for tp_business_comment.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.stars
     *
     * @return the value of tp_business_comment.stars
     *
     * @mbggenerated
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.stars
     *
     * @param stars the value for tp_business_comment.stars
     *
     * @mbggenerated
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.user_id
     *
     * @return the value of tp_business_comment.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.user_id
     *
     * @param userId the value for tp_business_comment.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.parent_id
     *
     * @return the value of tp_business_comment.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.parent_id
     *
     * @param parentId the value for tp_business_comment.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.add_time
     *
     * @return the value of tp_business_comment.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.add_time
     *
     * @param addTime the value for tp_business_comment.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_comment.tag
     *
     * @return the value of tp_business_comment.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_comment.tag
     *
     * @param tag the value for tp_business_comment.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}