package com.citytuike.model;

import java.math.BigDecimal;

public class TpBusinessCashFace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash_face.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash_face.bond
     *
     * @mbggenerated
     */
    private double bond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash_face.face_cash_start
     *
     * @mbggenerated
     */
    private double faceCashStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash_face.face_cash_end
     *
     * @mbggenerated
     */
    private double faceCashEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_business_cash_face.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash_face.id
     *
     * @return the value of tp_business_cash_face.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash_face.id
     *
     * @param id the value for tp_business_cash_face.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash_face.bond
     *
     * @return the value of tp_business_cash_face.bond
     *
     * @mbggenerated
     */
    public double getBond() {
        return bond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash_face.bond
     *
     * @param bond the value for tp_business_cash_face.bond
     *
     * @mbggenerated
     */
    public void setBond(double bond) {
        this.bond = bond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash_face.face_cash_start
     *
     * @return the value of tp_business_cash_face.face_cash_start
     *
     * @mbggenerated
     */
    public double getFaceCashStart() {
        return faceCashStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash_face.face_cash_start
     *
     * @param faceCashStart the value for tp_business_cash_face.face_cash_start
     *
     * @mbggenerated
     */
    public void setFaceCashStart(double faceCashStart) {
        this.faceCashStart = faceCashStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash_face.face_cash_end
     *
     * @return the value of tp_business_cash_face.face_cash_end
     *
     * @mbggenerated
     */
    public double getFaceCashEnd() {
        return faceCashEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash_face.face_cash_end
     *
     * @param faceCashEnd the value for tp_business_cash_face.face_cash_end
     *
     * @mbggenerated
     */
    public void setFaceCashEnd(double faceCashEnd) {
        this.faceCashEnd = faceCashEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_business_cash_face.add_time
     *
     * @return the value of tp_business_cash_face.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_business_cash_face.add_time
     *
     * @param addTime the value for tp_business_cash_face.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }
}