package com.citytuike.model;

public class TpChatFriendList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.room_id
     *
     * @mbggenerated
     */
    private String roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.from
     *
     * @mbggenerated
     */
    private String from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.to
     *
     * @mbggenerated
     */
    private String to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_friend_list.is_read
     *
     * @mbggenerated
     */
    private Integer isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.id
     *
     * @return the value of tp_chat_friend_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.id
     *
     * @param id the value for tp_chat_friend_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.room_id
     *
     * @return the value of tp_chat_friend_list.room_id
     *
     * @mbggenerated
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.room_id
     *
     * @param roomId the value for tp_chat_friend_list.room_id
     *
     * @mbggenerated
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId == null ? null : roomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.from
     *
     * @return the value of tp_chat_friend_list.from
     *
     * @mbggenerated
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.from
     *
     * @param from the value for tp_chat_friend_list.from
     *
     * @mbggenerated
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.to
     *
     * @return the value of tp_chat_friend_list.to
     *
     * @mbggenerated
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.to
     *
     * @param to the value for tp_chat_friend_list.to
     *
     * @mbggenerated
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.message
     *
     * @return the value of tp_chat_friend_list.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.message
     *
     * @param message the value for tp_chat_friend_list.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.update_time
     *
     * @return the value of tp_chat_friend_list.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.update_time
     *
     * @param updateTime the value for tp_chat_friend_list.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_friend_list.is_read
     *
     * @return the value of tp_chat_friend_list.is_read
     *
     * @mbggenerated
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_friend_list.is_read
     *
     * @param isRead the value for tp_chat_friend_list.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }
}