package com.citytuike.model;

public class TpChatLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.from
     *
     * @mbggenerated
     */
    private String from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.to
     *
     * @mbggenerated
     */
    private String to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.room
     *
     * @mbggenerated
     */
    private String room;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.msg_id
     *
     * @mbggenerated
     */
    private String msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.is_read
     *
     * @mbggenerated
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_chat_log.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.id
     *
     * @return the value of tp_chat_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.id
     *
     * @param id the value for tp_chat_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.from
     *
     * @return the value of tp_chat_log.from
     *
     * @mbggenerated
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.from
     *
     * @param from the value for tp_chat_log.from
     *
     * @mbggenerated
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.to
     *
     * @return the value of tp_chat_log.to
     *
     * @mbggenerated
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.to
     *
     * @param to the value for tp_chat_log.to
     *
     * @mbggenerated
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.add_time
     *
     * @return the value of tp_chat_log.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.add_time
     *
     * @param addTime the value for tp_chat_log.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.room
     *
     * @return the value of tp_chat_log.room
     *
     * @mbggenerated
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.room
     *
     * @param room the value for tp_chat_log.room
     *
     * @mbggenerated
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.msg_id
     *
     * @return the value of tp_chat_log.msg_id
     *
     * @mbggenerated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.msg_id
     *
     * @param msgId the value for tp_chat_log.msg_id
     *
     * @mbggenerated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.is_read
     *
     * @return the value of tp_chat_log.is_read
     *
     * @mbggenerated
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.is_read
     *
     * @param isRead the value for tp_chat_log.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_chat_log.content
     *
     * @return the value of tp_chat_log.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_chat_log.content
     *
     * @param content the value for tp_chat_log.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}