package com.citytuike.model;

public class TpDevicePlay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device_play.device_id
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device_play.region_id
     *
     * @mbggenerated
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device_play.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device_play.days
     *
     * @mbggenerated
     */
    private Integer days;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device_play.device_id
     *
     * @return the value of tp_device_play.device_id
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device_play.device_id
     *
     * @param deviceId the value for tp_device_play.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device_play.region_id
     *
     * @return the value of tp_device_play.region_id
     *
     * @mbggenerated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device_play.region_id
     *
     * @param regionId the value for tp_device_play.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device_play.order_num
     *
     * @return the value of tp_device_play.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device_play.order_num
     *
     * @param orderNum the value for tp_device_play.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device_play.days
     *
     * @return the value of tp_device_play.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device_play.days
     *
     * @param days the value for tp_device_play.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }
}