package com.citytuike.model;

import java.math.BigDecimal;

public class TpDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.device_sn
     *
     * @mbggenerated
     */
    private String deviceSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.ad_position_id
     *
     * @mbggenerated
     */
    private Integer adPositionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.qrscene
     *
     * @mbggenerated
     */
    private String qrscene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.iot_id
     *
     * @mbggenerated
     */
    private String iotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.product_key
     *
     * @mbggenerated
     */
    private String productKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.device_name
     *
     * @mbggenerated
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.device_secret
     *
     * @mbggenerated
     */
    private String deviceSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.paper_number
     *
     * @mbggenerated
     */
    private Integer paperNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.paper_send
     *
     * @mbggenerated
     */
    private Integer paperSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.paper_inventory
     *
     * @mbggenerated
     */
    private Integer paperInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.income
     *
     * @mbggenerated
     */
    private BigDecimal income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.one_income
     *
     * @mbggenerated
     */
    private BigDecimal oneIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.capacity
     *
     * @mbggenerated
     */
    private Integer capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.active_time
     *
     * @mbggenerated
     */
    private Integer activeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.no_send
     *
     * @mbggenerated
     */
    private Boolean noSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.open_status
     *
     * @mbggenerated
     */
    private Boolean openStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.online
     *
     * @mbggenerated
     */
    private Boolean online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.landmark_picture
     *
     * @mbggenerated
     */
    private String landmarkPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.district
     *
     * @mbggenerated
     */
    private Integer district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.is_active
     *
     * @mbggenerated
     */
    private Byte isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.order_id
     *
     * @mbggenerated
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.distribution_time
     *
     * @mbggenerated
     */
    private Integer distributionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.active_code
     *
     * @mbggenerated
     */
    private String activeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.shipping_sn
     *
     * @mbggenerated
     */
    private String shippingSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.shipping_name
     *
     * @mbggenerated
     */
    private String shippingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.today_num
     *
     * @mbggenerated
     */
    private Integer todayNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.today_time
     *
     * @mbggenerated
     */
    private Integer todayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.lack_paper
     *
     * @mbggenerated
     */
    private Integer lackPaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.old_order_id
     *
     * @mbggenerated
     */
    private Integer oldOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.is_settled
     *
     * @mbggenerated
     */
    private Boolean isSettled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.settled_money
     *
     * @mbggenerated
     */
    private BigDecimal settledMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.run_status
     *
     * @mbggenerated
     */
    private Integer runStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.position_lock
     *
     * @mbggenerated
     */
    private Integer positionLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.distance
     *
     * @mbggenerated
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.limit_config
     *
     * @mbggenerated
     */
    private String limitConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.warning_number
     *
     * @mbggenerated
     */
    private Integer warningNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.byname
     *
     * @mbggenerated
     */
    private String byname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_device.accept_user
     *
     * @mbggenerated
     */
    private Integer acceptUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.id
     *
     * @return the value of tp_device.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.id
     *
     * @param id the value for tp_device.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.device_sn
     *
     * @return the value of tp_device.device_sn
     *
     * @mbggenerated
     */
    public String getDeviceSn() {
        return deviceSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.device_sn
     *
     * @param deviceSn the value for tp_device.device_sn
     *
     * @mbggenerated
     */
    public void setDeviceSn(String deviceSn) {
        this.deviceSn = deviceSn == null ? null : deviceSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.ad_position_id
     *
     * @return the value of tp_device.ad_position_id
     *
     * @mbggenerated
     */
    public Integer getAdPositionId() {
        return adPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.ad_position_id
     *
     * @param adPositionId the value for tp_device.ad_position_id
     *
     * @mbggenerated
     */
    public void setAdPositionId(Integer adPositionId) {
        this.adPositionId = adPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.qrscene
     *
     * @return the value of tp_device.qrscene
     *
     * @mbggenerated
     */
    public String getQrscene() {
        return qrscene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.qrscene
     *
     * @param qrscene the value for tp_device.qrscene
     *
     * @mbggenerated
     */
    public void setQrscene(String qrscene) {
        this.qrscene = qrscene == null ? null : qrscene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.iot_id
     *
     * @return the value of tp_device.iot_id
     *
     * @mbggenerated
     */
    public String getIotId() {
        return iotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.iot_id
     *
     * @param iotId the value for tp_device.iot_id
     *
     * @mbggenerated
     */
    public void setIotId(String iotId) {
        this.iotId = iotId == null ? null : iotId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.product_key
     *
     * @return the value of tp_device.product_key
     *
     * @mbggenerated
     */
    public String getProductKey() {
        return productKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.product_key
     *
     * @param productKey the value for tp_device.product_key
     *
     * @mbggenerated
     */
    public void setProductKey(String productKey) {
        this.productKey = productKey == null ? null : productKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.device_name
     *
     * @return the value of tp_device.device_name
     *
     * @mbggenerated
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.device_name
     *
     * @param deviceName the value for tp_device.device_name
     *
     * @mbggenerated
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.device_secret
     *
     * @return the value of tp_device.device_secret
     *
     * @mbggenerated
     */
    public String getDeviceSecret() {
        return deviceSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.device_secret
     *
     * @param deviceSecret the value for tp_device.device_secret
     *
     * @mbggenerated
     */
    public void setDeviceSecret(String deviceSecret) {
        this.deviceSecret = deviceSecret == null ? null : deviceSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.add_time
     *
     * @return the value of tp_device.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.add_time
     *
     * @param addTime the value for tp_device.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.user_id
     *
     * @return the value of tp_device.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.user_id
     *
     * @param userId the value for tp_device.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.paper_number
     *
     * @return the value of tp_device.paper_number
     *
     * @mbggenerated
     */
    public Integer getPaperNumber() {
        return paperNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.paper_number
     *
     * @param paperNumber the value for tp_device.paper_number
     *
     * @mbggenerated
     */
    public void setPaperNumber(Integer paperNumber) {
        this.paperNumber = paperNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.paper_send
     *
     * @return the value of tp_device.paper_send
     *
     * @mbggenerated
     */
    public Integer getPaperSend() {
        return paperSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.paper_send
     *
     * @param paperSend the value for tp_device.paper_send
     *
     * @mbggenerated
     */
    public void setPaperSend(Integer paperSend) {
        this.paperSend = paperSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.paper_inventory
     *
     * @return the value of tp_device.paper_inventory
     *
     * @mbggenerated
     */
    public Integer getPaperInventory() {
        return paperInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.paper_inventory
     *
     * @param paperInventory the value for tp_device.paper_inventory
     *
     * @mbggenerated
     */
    public void setPaperInventory(Integer paperInventory) {
        this.paperInventory = paperInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.income
     *
     * @return the value of tp_device.income
     *
     * @mbggenerated
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.income
     *
     * @param income the value for tp_device.income
     *
     * @mbggenerated
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.one_income
     *
     * @return the value of tp_device.one_income
     *
     * @mbggenerated
     */
    public BigDecimal getOneIncome() {
        return oneIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.one_income
     *
     * @param oneIncome the value for tp_device.one_income
     *
     * @mbggenerated
     */
    public void setOneIncome(BigDecimal oneIncome) {
        this.oneIncome = oneIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.capacity
     *
     * @return the value of tp_device.capacity
     *
     * @mbggenerated
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.capacity
     *
     * @param capacity the value for tp_device.capacity
     *
     * @mbggenerated
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.active_time
     *
     * @return the value of tp_device.active_time
     *
     * @mbggenerated
     */
    public Integer getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.active_time
     *
     * @param activeTime the value for tp_device.active_time
     *
     * @mbggenerated
     */
    public void setActiveTime(Integer activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.no_send
     *
     * @return the value of tp_device.no_send
     *
     * @mbggenerated
     */
    public Boolean getNoSend() {
        return noSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.no_send
     *
     * @param noSend the value for tp_device.no_send
     *
     * @mbggenerated
     */
    public void setNoSend(Boolean noSend) {
        this.noSend = noSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.open_status
     *
     * @return the value of tp_device.open_status
     *
     * @mbggenerated
     */
    public Boolean getOpenStatus() {
        return openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.open_status
     *
     * @param openStatus the value for tp_device.open_status
     *
     * @mbggenerated
     */
    public void setOpenStatus(Boolean openStatus) {
        this.openStatus = openStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.online
     *
     * @return the value of tp_device.online
     *
     * @mbggenerated
     */
    public Boolean getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.online
     *
     * @param online the value for tp_device.online
     *
     * @mbggenerated
     */
    public void setOnline(Boolean online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.landmark_picture
     *
     * @return the value of tp_device.landmark_picture
     *
     * @mbggenerated
     */
    public String getLandmarkPicture() {
        return landmarkPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.landmark_picture
     *
     * @param landmarkPicture the value for tp_device.landmark_picture
     *
     * @mbggenerated
     */
    public void setLandmarkPicture(String landmarkPicture) {
        this.landmarkPicture = landmarkPicture == null ? null : landmarkPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.province
     *
     * @return the value of tp_device.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.province
     *
     * @param province the value for tp_device.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.city
     *
     * @return the value of tp_device.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.city
     *
     * @param city the value for tp_device.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.district
     *
     * @return the value of tp_device.district
     *
     * @mbggenerated
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.district
     *
     * @param district the value for tp_device.district
     *
     * @mbggenerated
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.is_active
     *
     * @return the value of tp_device.is_active
     *
     * @mbggenerated
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.is_active
     *
     * @param isActive the value for tp_device.is_active
     *
     * @mbggenerated
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.order_id
     *
     * @return the value of tp_device.order_id
     *
     * @mbggenerated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.order_id
     *
     * @param orderId the value for tp_device.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.goods_id
     *
     * @return the value of tp_device.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.goods_id
     *
     * @param goodsId the value for tp_device.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.distribution_time
     *
     * @return the value of tp_device.distribution_time
     *
     * @mbggenerated
     */
    public Integer getDistributionTime() {
        return distributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.distribution_time
     *
     * @param distributionTime the value for tp_device.distribution_time
     *
     * @mbggenerated
     */
    public void setDistributionTime(Integer distributionTime) {
        this.distributionTime = distributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.address
     *
     * @return the value of tp_device.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.address
     *
     * @param address the value for tp_device.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.longitude
     *
     * @return the value of tp_device.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.longitude
     *
     * @param longitude the value for tp_device.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.latitude
     *
     * @return the value of tp_device.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.latitude
     *
     * @param latitude the value for tp_device.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.active_code
     *
     * @return the value of tp_device.active_code
     *
     * @mbggenerated
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.active_code
     *
     * @param activeCode the value for tp_device.active_code
     *
     * @mbggenerated
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.shipping_sn
     *
     * @return the value of tp_device.shipping_sn
     *
     * @mbggenerated
     */
    public String getShippingSn() {
        return shippingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.shipping_sn
     *
     * @param shippingSn the value for tp_device.shipping_sn
     *
     * @mbggenerated
     */
    public void setShippingSn(String shippingSn) {
        this.shippingSn = shippingSn == null ? null : shippingSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.shipping_name
     *
     * @return the value of tp_device.shipping_name
     *
     * @mbggenerated
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.shipping_name
     *
     * @param shippingName the value for tp_device.shipping_name
     *
     * @mbggenerated
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName == null ? null : shippingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.today_num
     *
     * @return the value of tp_device.today_num
     *
     * @mbggenerated
     */
    public Integer getTodayNum() {
        return todayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.today_num
     *
     * @param todayNum the value for tp_device.today_num
     *
     * @mbggenerated
     */
    public void setTodayNum(Integer todayNum) {
        this.todayNum = todayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.today_time
     *
     * @return the value of tp_device.today_time
     *
     * @mbggenerated
     */
    public Integer getTodayTime() {
        return todayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.today_time
     *
     * @param todayTime the value for tp_device.today_time
     *
     * @mbggenerated
     */
    public void setTodayTime(Integer todayTime) {
        this.todayTime = todayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.app_version
     *
     * @return the value of tp_device.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.app_version
     *
     * @param appVersion the value for tp_device.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.lack_paper
     *
     * @return the value of tp_device.lack_paper
     *
     * @mbggenerated
     */
    public Integer getLackPaper() {
        return lackPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.lack_paper
     *
     * @param lackPaper the value for tp_device.lack_paper
     *
     * @mbggenerated
     */
    public void setLackPaper(Integer lackPaper) {
        this.lackPaper = lackPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.old_order_id
     *
     * @return the value of tp_device.old_order_id
     *
     * @mbggenerated
     */
    public Integer getOldOrderId() {
        return oldOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.old_order_id
     *
     * @param oldOrderId the value for tp_device.old_order_id
     *
     * @mbggenerated
     */
    public void setOldOrderId(Integer oldOrderId) {
        this.oldOrderId = oldOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.is_settled
     *
     * @return the value of tp_device.is_settled
     *
     * @mbggenerated
     */
    public Boolean getIsSettled() {
        return isSettled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.is_settled
     *
     * @param isSettled the value for tp_device.is_settled
     *
     * @mbggenerated
     */
    public void setIsSettled(Boolean isSettled) {
        this.isSettled = isSettled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.settled_money
     *
     * @return the value of tp_device.settled_money
     *
     * @mbggenerated
     */
    public BigDecimal getSettledMoney() {
        return settledMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.settled_money
     *
     * @param settledMoney the value for tp_device.settled_money
     *
     * @mbggenerated
     */
    public void setSettledMoney(BigDecimal settledMoney) {
        this.settledMoney = settledMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.run_status
     *
     * @return the value of tp_device.run_status
     *
     * @mbggenerated
     */
    public Integer getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.run_status
     *
     * @param runStatus the value for tp_device.run_status
     *
     * @mbggenerated
     */
    public void setRunStatus(Integer runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.position_lock
     *
     * @return the value of tp_device.position_lock
     *
     * @mbggenerated
     */
    public Integer getPositionLock() {
        return positionLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.position_lock
     *
     * @param positionLock the value for tp_device.position_lock
     *
     * @mbggenerated
     */
    public void setPositionLock(Integer positionLock) {
        this.positionLock = positionLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.distance
     *
     * @return the value of tp_device.distance
     *
     * @mbggenerated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.distance
     *
     * @param distance the value for tp_device.distance
     *
     * @mbggenerated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.limit_config
     *
     * @return the value of tp_device.limit_config
     *
     * @mbggenerated
     */
    public String getLimitConfig() {
        return limitConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.limit_config
     *
     * @param limitConfig the value for tp_device.limit_config
     *
     * @mbggenerated
     */
    public void setLimitConfig(String limitConfig) {
        this.limitConfig = limitConfig == null ? null : limitConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.warning_number
     *
     * @return the value of tp_device.warning_number
     *
     * @mbggenerated
     */
    public Integer getWarningNumber() {
        return warningNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.warning_number
     *
     * @param warningNumber the value for tp_device.warning_number
     *
     * @mbggenerated
     */
    public void setWarningNumber(Integer warningNumber) {
        this.warningNumber = warningNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.byname
     *
     * @return the value of tp_device.byname
     *
     * @mbggenerated
     */
    public String getByname() {
        return byname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.byname
     *
     * @param byname the value for tp_device.byname
     *
     * @mbggenerated
     */
    public void setByname(String byname) {
        this.byname = byname == null ? null : byname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_device.accept_user
     *
     * @return the value of tp_device.accept_user
     *
     * @mbggenerated
     */
    public Integer getAcceptUser() {
        return acceptUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_device.accept_user
     *
     * @param acceptUser the value for tp_device.accept_user
     *
     * @mbggenerated
     */
    public void setAcceptUser(Integer acceptUser) {
        this.acceptUser = acceptUser;
    }
}