package com.citytuike.model;

public class TpDynamic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.fabulous
     *
     * @mbggenerated
     */
    private Integer fabulous;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.nums
     *
     * @mbggenerated
     */
    private Integer nums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.view_status
     *
     * @mbggenerated
     */
    private Integer viewStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_dynamic.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.id
     *
     * @return the value of tp_dynamic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.id
     *
     * @param id the value for tp_dynamic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.user_id
     *
     * @return the value of tp_dynamic.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.user_id
     *
     * @param userId the value for tp_dynamic.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.image
     *
     * @return the value of tp_dynamic.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.image
     *
     * @param image the value for tp_dynamic.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.add_time
     *
     * @return the value of tp_dynamic.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.add_time
     *
     * @param addTime the value for tp_dynamic.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.fabulous
     *
     * @return the value of tp_dynamic.fabulous
     *
     * @mbggenerated
     */
    public Integer getFabulous() {
        return fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.fabulous
     *
     * @param fabulous the value for tp_dynamic.fabulous
     *
     * @mbggenerated
     */
    public void setFabulous(Integer fabulous) {
        this.fabulous = fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.nums
     *
     * @return the value of tp_dynamic.nums
     *
     * @mbggenerated
     */
    public Integer getNums() {
        return nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.nums
     *
     * @param nums the value for tp_dynamic.nums
     *
     * @mbggenerated
     */
    public void setNums(Integer nums) {
        this.nums = nums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.view_status
     *
     * @return the value of tp_dynamic.view_status
     *
     * @mbggenerated
     */
    public Integer getViewStatus() {
        return viewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.view_status
     *
     * @param viewStatus the value for tp_dynamic.view_status
     *
     * @mbggenerated
     */
    public void setViewStatus(Integer viewStatus) {
        this.viewStatus = viewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.is_delete
     *
     * @return the value of tp_dynamic.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.is_delete
     *
     * @param isDelete the value for tp_dynamic.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_dynamic.content
     *
     * @return the value of tp_dynamic.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_dynamic.content
     *
     * @param content the value for tp_dynamic.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}