package com.citytuike.model;

public class TpFabulous {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_fabulous.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_fabulous.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_fabulous.d_id
     *
     * @mbggenerated
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_fabulous.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_fabulous.id
     *
     * @return the value of tp_fabulous.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_fabulous.id
     *
     * @param id the value for tp_fabulous.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_fabulous.user_id
     *
     * @return the value of tp_fabulous.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_fabulous.user_id
     *
     * @param userId the value for tp_fabulous.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_fabulous.d_id
     *
     * @return the value of tp_fabulous.d_id
     *
     * @mbggenerated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_fabulous.d_id
     *
     * @param dId the value for tp_fabulous.d_id
     *
     * @mbggenerated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_fabulous.add_time
     *
     * @return the value of tp_fabulous.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_fabulous.add_time
     *
     * @param addTime the value for tp_fabulous.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }
}