package com.citytuike.model;

import java.util.Date;

public class TpPhotoAlbumTmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.tmp_id
     *
     * @mbggenerated
     */
    private Integer tmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.route_url
     *
     * @mbggenerated
     */
    private String routeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp.classify_id
     *
     * @mbggenerated
     */
    private Integer classifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.tmp_id
     *
     * @return the value of tp_photo_album_tmp.tmp_id
     *
     * @mbggenerated
     */
    public Integer getTmpId() {
        return tmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.tmp_id
     *
     * @param tmpId the value for tp_photo_album_tmp.tmp_id
     *
     * @mbggenerated
     */
    public void setTmpId(Integer tmpId) {
        this.tmpId = tmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.image_url
     *
     * @return the value of tp_photo_album_tmp.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.image_url
     *
     * @param imageUrl the value for tp_photo_album_tmp.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.status
     *
     * @return the value of tp_photo_album_tmp.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.status
     *
     * @param status the value for tp_photo_album_tmp.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.sort
     *
     * @return the value of tp_photo_album_tmp.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.sort
     *
     * @param sort the value for tp_photo_album_tmp.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.add_time
     *
     * @return the value of tp_photo_album_tmp.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.add_time
     *
     * @param addTime the value for tp_photo_album_tmp.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.title
     *
     * @return the value of tp_photo_album_tmp.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.title
     *
     * @param title the value for tp_photo_album_tmp.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.route_url
     *
     * @return the value of tp_photo_album_tmp.route_url
     *
     * @mbggenerated
     */
    public String getRouteUrl() {
        return routeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.route_url
     *
     * @param routeUrl the value for tp_photo_album_tmp.route_url
     *
     * @mbggenerated
     */
    public void setRouteUrl(String routeUrl) {
        this.routeUrl = routeUrl == null ? null : routeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp.classify_id
     *
     * @return the value of tp_photo_album_tmp.classify_id
     *
     * @mbggenerated
     */
    public Integer getClassifyId() {
        return classifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp.classify_id
     *
     * @param classifyId the value for tp_photo_album_tmp.classify_id
     *
     * @mbggenerated
     */
    public void setClassifyId(Integer classifyId) {
        this.classifyId = classifyId;
    }
}