package com.citytuike.model;

public class TpPhotoAlbumTmpClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp_classify.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp_classify.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp_classify.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp_classify.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_tmp_classify.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp_classify.id
     *
     * @return the value of tp_photo_album_tmp_classify.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp_classify.id
     *
     * @param id the value for tp_photo_album_tmp_classify.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp_classify.name
     *
     * @return the value of tp_photo_album_tmp_classify.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp_classify.name
     *
     * @param name the value for tp_photo_album_tmp_classify.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp_classify.sort
     *
     * @return the value of tp_photo_album_tmp_classify.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp_classify.sort
     *
     * @param sort the value for tp_photo_album_tmp_classify.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp_classify.status
     *
     * @return the value of tp_photo_album_tmp_classify.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp_classify.status
     *
     * @param status the value for tp_photo_album_tmp_classify.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_tmp_classify.icon
     *
     * @return the value of tp_photo_album_tmp_classify.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_tmp_classify.icon
     *
     * @param icon the value for tp_photo_album_tmp_classify.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}