package com.citytuike.model;

import java.math.BigDecimal;

public class TpPhotoAlbumAd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.ad_id
     *
     * @mbggenerated
     */
    private Integer adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.price
     *
     * @mbggenerated
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.text_2
     *
     * @mbggenerated
     */
    private String text2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.text_3
     *
     * @mbggenerated
     */
    private String text3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_ad.ori_price
     *
     * @mbggenerated
     */
    private double oriPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.ad_id
     *
     * @return the value of tp_photo_album_ad.ad_id
     *
     * @mbggenerated
     */
    public Integer getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.ad_id
     *
     * @param adId the value for tp_photo_album_ad.ad_id
     *
     * @mbggenerated
     */
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.desc
     *
     * @return the value of tp_photo_album_ad.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.desc
     *
     * @param desc the value for tp_photo_album_ad.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.image
     *
     * @return the value of tp_photo_album_ad.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.image
     *
     * @param image the value for tp_photo_album_ad.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.model
     *
     * @return the value of tp_photo_album_ad.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.model
     *
     * @param model the value for tp_photo_album_ad.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.price
     *
     * @return the value of tp_photo_album_ad.price
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.price
     *
     * @param price the value for tp_photo_album_ad.price
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.link
     *
     * @return the value of tp_photo_album_ad.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.link
     *
     * @param link the value for tp_photo_album_ad.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.text_2
     *
     * @return the value of tp_photo_album_ad.text_2
     *
     * @mbggenerated
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.text_2
     *
     * @param text2 the value for tp_photo_album_ad.text_2
     *
     * @mbggenerated
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.text_3
     *
     * @return the value of tp_photo_album_ad.text_3
     *
     * @mbggenerated
     */
    public String getText3() {
        return text3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.text_3
     *
     * @param text3 the value for tp_photo_album_ad.text_3
     *
     * @mbggenerated
     */
    public void setText3(String text3) {
        this.text3 = text3 == null ? null : text3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.user_id
     *
     * @return the value of tp_photo_album_ad.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.user_id
     *
     * @param userId the value for tp_photo_album_ad.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_ad.ori_price
     *
     * @return the value of tp_photo_album_ad.ori_price
     *
     * @mbggenerated
     */
    public double getOriPrice() {
        return oriPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_ad.ori_price
     *
     * @param oriPrice the value for tp_photo_album_ad.ori_price
     *
     * @mbggenerated
     */
    public void setOriPrice(double oriPrice) {
        this.oriPrice = oriPrice;
    }
}