package com.citytuike.model;

import java.util.Date;

public class TpPhotoAlbumUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.ad_id
     *
     * @mbggenerated
     */
    private String adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.music_url
     *
     * @mbggenerated
     */
    private String musicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.pv
     *
     * @mbggenerated
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.tmp_id
     *
     * @mbggenerated
     */
    private Integer tmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.share
     *
     * @mbggenerated
     */
    private Integer share;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_photo_album_user.extend
     *
     * @mbggenerated
     */
    private String extend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.p_id
     *
     * @return the value of tp_photo_album_user.p_id
     *
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.p_id
     *
     * @param pId the value for tp_photo_album_user.p_id
     *
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.desc
     *
     * @return the value of tp_photo_album_user.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.desc
     *
     * @param desc the value for tp_photo_album_user.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.ad_id
     *
     * @return the value of tp_photo_album_user.ad_id
     *
     * @mbggenerated
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.ad_id
     *
     * @param adId the value for tp_photo_album_user.ad_id
     *
     * @mbggenerated
     */
    public void setAdId(String adId) {
        this.adId = adId == null ? null : adId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.music_url
     *
     * @return the value of tp_photo_album_user.music_url
     *
     * @mbggenerated
     */
    public String getMusicUrl() {
        return musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.music_url
     *
     * @param musicUrl the value for tp_photo_album_user.music_url
     *
     * @mbggenerated
     */
    public void setMusicUrl(String musicUrl) {
        this.musicUrl = musicUrl == null ? null : musicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.add_time
     *
     * @return the value of tp_photo_album_user.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.add_time
     *
     * @param addTime the value for tp_photo_album_user.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.status
     *
     * @return the value of tp_photo_album_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.status
     *
     * @param status the value for tp_photo_album_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.pv
     *
     * @return the value of tp_photo_album_user.pv
     *
     * @mbggenerated
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.pv
     *
     * @param pv the value for tp_photo_album_user.pv
     *
     * @mbggenerated
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.sort
     *
     * @return the value of tp_photo_album_user.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.sort
     *
     * @param sort the value for tp_photo_album_user.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.user_id
     *
     * @return the value of tp_photo_album_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.user_id
     *
     * @param userId the value for tp_photo_album_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.tmp_id
     *
     * @return the value of tp_photo_album_user.tmp_id
     *
     * @mbggenerated
     */
    public Integer getTmpId() {
        return tmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.tmp_id
     *
     * @param tmpId the value for tp_photo_album_user.tmp_id
     *
     * @mbggenerated
     */
    public void setTmpId(Integer tmpId) {
        this.tmpId = tmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.update_time
     *
     * @return the value of tp_photo_album_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.update_time
     *
     * @param updateTime the value for tp_photo_album_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.share
     *
     * @return the value of tp_photo_album_user.share
     *
     * @mbggenerated
     */
    public Integer getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.share
     *
     * @param share the value for tp_photo_album_user.share
     *
     * @mbggenerated
     */
    public void setShare(Integer share) {
        this.share = share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.delete_time
     *
     * @return the value of tp_photo_album_user.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.delete_time
     *
     * @param deleteTime the value for tp_photo_album_user.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_photo_album_user.extend
     *
     * @return the value of tp_photo_album_user.extend
     *
     * @mbggenerated
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_photo_album_user.extend
     *
     * @param extend the value for tp_photo_album_user.extend
     *
     * @mbggenerated
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }
}