package com.citytuike.model;

public class TpReplay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_replay.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_replay.d_id
     *
     * @mbggenerated
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_replay.add_time
     *
     * @mbggenerated
     */
    private Integer addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_replay.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_replay.replay_content
     *
     * @mbggenerated
     */
    private String replayContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_replay.id
     *
     * @return the value of tp_replay.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_replay.id
     *
     * @param id the value for tp_replay.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_replay.d_id
     *
     * @return the value of tp_replay.d_id
     *
     * @mbggenerated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_replay.d_id
     *
     * @param dId the value for tp_replay.d_id
     *
     * @mbggenerated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_replay.add_time
     *
     * @return the value of tp_replay.add_time
     *
     * @mbggenerated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_replay.add_time
     *
     * @param addTime the value for tp_replay.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_replay.user_id
     *
     * @return the value of tp_replay.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_replay.user_id
     *
     * @param userId the value for tp_replay.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_replay.replay_content
     *
     * @return the value of tp_replay.replay_content
     *
     * @mbggenerated
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_replay.replay_content
     *
     * @param replayContent the value for tp_replay.replay_content
     *
     * @mbggenerated
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }
}