package com.citytuike.model;

import java.util.Date;

public class TpUserFriendApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.friend_user_id
     *
     * @mbggenerated
     */
    private Integer friendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friend_apply.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.id
     *
     * @return the value of tp_user_friend_apply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.id
     *
     * @param id the value for tp_user_friend_apply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.user_id
     *
     * @return the value of tp_user_friend_apply.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.user_id
     *
     * @param userId the value for tp_user_friend_apply.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.friend_user_id
     *
     * @return the value of tp_user_friend_apply.friend_user_id
     *
     * @mbggenerated
     */
    public Integer getFriendUserId() {
        return friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.friend_user_id
     *
     * @param friendUserId the value for tp_user_friend_apply.friend_user_id
     *
     * @mbggenerated
     */
    public void setFriendUserId(Integer friendUserId) {
        this.friendUserId = friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.msg
     *
     * @return the value of tp_user_friend_apply.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.msg
     *
     * @param msg the value for tp_user_friend_apply.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.state
     *
     * @return the value of tp_user_friend_apply.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.state
     *
     * @param state the value for tp_user_friend_apply.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.created_at
     *
     * @return the value of tp_user_friend_apply.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.created_at
     *
     * @param createdAt the value for tp_user_friend_apply.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friend_apply.updated_at
     *
     * @return the value of tp_user_friend_apply.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friend_apply.updated_at
     *
     * @param updatedAt the value for tp_user_friend_apply.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}