package com.citytuike.model;

import java.util.Date;

public class TpUserFriends {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.friend_user_id
     *
     * @mbggenerated
     */
    private Integer friendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.invalid
     * 是否失效
     * @mbggenerated
     */
    private Integer invalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_user_friends.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.id
     *
     * @return the value of tp_user_friends.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.id
     *
     * @param id the value for tp_user_friends.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.user_id
     *
     * @return the value of tp_user_friends.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.user_id
     *
     * @param userId the value for tp_user_friends.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.friend_user_id
     *
     * @return the value of tp_user_friends.friend_user_id
     *
     * @mbggenerated
     */
    public Integer getFriendUserId() {
        return friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.friend_user_id
     *
     * @param friendUserId the value for tp_user_friends.friend_user_id
     *
     * @mbggenerated
     */
    public void setFriendUserId(Integer friendUserId) {
        this.friendUserId = friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.remark
     *
     * @return the value of tp_user_friends.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.remark
     *
     * @param remark the value for tp_user_friends.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.invalid
     *
     * @return the value of tp_user_friends.invalid
     *
     * @mbggenerated
     */
    public Integer getInvalid() {
        return invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.invalid
     *
     * @param invalid the value for tp_user_friends.invalid
     *
     * @mbggenerated
     */
    public void setInvalid(Integer invalid) {
        this.invalid = invalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.created_at
     *
     * @return the value of tp_user_friends.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.created_at
     *
     * @param createdAt the value for tp_user_friends.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_user_friends.updated_at
     *
     * @return the value of tp_user_friends.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_user_friends.updated_at
     *
     * @param updatedAt the value for tp_user_friends.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}