package com.citytuike.model;

import java.math.BigDecimal;
import java.util.Date;

public class TpUsersGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.price
     *
     * @mbggenerated
     */
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.sku
     *
     * @mbggenerated
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.freight
     *
     * @mbggenerated
     */
    private String freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.goods_desc
     *
     * @mbggenerated
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.adopt_status
     *
     * @mbggenerated
     */
    private Integer adoptStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.shelf_status
     *
     * @mbggenerated
     */
    private Integer shelfStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tp_users_goods.image_detail
     *
     * @mbggenerated
     */
    private String imageDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.id
     *
     * @return the value of tp_users_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.id
     *
     * @param id the value for tp_users_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.user_id
     *
     * @return the value of tp_users_goods.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.user_id
     *
     * @param userId the value for tp_users_goods.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.goods_name
     *
     * @return the value of tp_users_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.goods_name
     *
     * @param goodsName the value for tp_users_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.image
     *
     * @return the value of tp_users_goods.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.image
     *
     * @param image the value for tp_users_goods.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.price
     *
     * @return the value of tp_users_goods.price
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.price
     *
     * @param price the value for tp_users_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.sku
     *
     * @return the value of tp_users_goods.sku
     *
     * @mbggenerated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.sku
     *
     * @param sku the value for tp_users_goods.sku
     *
     * @mbggenerated
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.freight
     *
     * @return the value of tp_users_goods.freight
     *
     * @mbggenerated
     */
    public String getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.freight
     *
     * @param freight the value for tp_users_goods.freight
     *
     * @mbggenerated
     */
    public void setFreight(String freight) {
        this.freight = freight == null ? null : freight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.goods_desc
     *
     * @return the value of tp_users_goods.goods_desc
     *
     * @mbggenerated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.goods_desc
     *
     * @param goodsDesc the value for tp_users_goods.goods_desc
     *
     * @mbggenerated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.add_time
     *
     * @return the value of tp_users_goods.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.add_time
     *
     * @param addTime the value for tp_users_goods.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.adopt_status
     *
     * @return the value of tp_users_goods.adopt_status
     *
     * @mbggenerated
     */
    public Integer getAdoptStatus() {
        return adoptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.adopt_status
     *
     * @param adoptStatus the value for tp_users_goods.adopt_status
     *
     * @mbggenerated
     */
    public void setAdoptStatus(Integer adoptStatus) {
        this.adoptStatus = adoptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.shelf_status
     *
     * @return the value of tp_users_goods.shelf_status
     *
     * @mbggenerated
     */
    public Integer getShelfStatus() {
        return shelfStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.shelf_status
     *
     * @param shelfStatus the value for tp_users_goods.shelf_status
     *
     * @mbggenerated
     */
    public void setShelfStatus(Integer shelfStatus) {
        this.shelfStatus = shelfStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.is_delete
     *
     * @return the value of tp_users_goods.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.is_delete
     *
     * @param isDelete the value for tp_users_goods.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.update_time
     *
     * @return the value of tp_users_goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.update_time
     *
     * @param updateTime the value for tp_users_goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tp_users_goods.image_detail
     *
     * @return the value of tp_users_goods.image_detail
     *
     * @mbggenerated
     */
    public String getImageDetail() {
        return imageDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tp_users_goods.image_detail
     *
     * @param imageDetail the value for tp_users_goods.image_detail
     *
     * @mbggenerated
     */
    public void setImageDetail(String imageDetail) {
        this.imageDetail = imageDetail == null ? null : imageDetail.trim();
    }
}