package com.citytuike.mapper;

import com.citytuike.model.TpAdPosition;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpAdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int insert(TpAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int insertSelective(TpAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    TpAdPosition selectByPrimaryKey(Integer positionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TpAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_ad_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpAdPosition record);

    List<TpAdPosition> findAdPositionByDeviceId(@Param("device_id") Integer device_id);
}