package com.citytuike.mapper;

import com.citytuike.model.TpApply;

public interface TpApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    int insert(TpApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    int insertSelective(TpApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    TpApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpApply record);
}