package com.citytuike.mapper;

import com.citytuike.model.TpBusinessCash;
import com.citytuike.model.TpGoods;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpBusinessCashMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    int insert(TpBusinessCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    TpBusinessCash selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessCash record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessCash record);

    List<TpBusinessCash> findAllCashByShare(@Param("businessId") Integer businessId);
}