package com.citytuike.mapper;

import com.citytuike.model.TpBusinessImages;

public interface TpBusinessImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    int insert(TpBusinessImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    TpBusinessImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessImages record);
}