package com.citytuike.mapper;

import com.citytuike.model.TpBusinessType;

import java.util.List;

public interface TpBusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    int insert(TpBusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    TpBusinessType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessType record);

    List<TpBusinessType> findAllBusinessType();
}