package com.citytuike.mapper;

import com.citytuike.model.TpBusinessSave;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpBusinessSaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    int insert(TpBusinessSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    TpBusinessSave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessSave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_save
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessSave record);

    List<TpBusinessSave> findAllSaveByOrder(@Param("orderSn") String orderSn);

    TpBusinessSave findSavaByCashId(@Param("cash_id") Integer cash_id);
}