package com.citytuike.mapper;

import com.citytuike.model.TpBusinessShare;
import com.citytuike.model.TpBusinessUseCash;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpBusinessShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    int insert(TpBusinessShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    TpBusinessShare selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessShare record);

    List<TpBusinessShare> findNearByBusiness(@Param("business_type") int business_type, @Param("geohash")String geohash, @Param("tuijian")int tuijian);

    TpBusinessShare findBusinessShareByUserId(@Param("user_id")Integer user_id);

    TpBusinessShare findBusinessShareByTag(@Param("business_id")Integer business_id, @Param("tag") String tag);

    int updataShareByTag(@Param("business_id") Integer business_id, @Param("tags") String tags);

    TpBusinessShare findBusinessShareByIdAndUserId(@Param("shop_id") int shop_id, @Param("user_id")Integer user_id);

    int getCount(@Param("type") String type, @Param("geohash") String geohash);

    List<TpBusinessShare> selectByPage(@Param("type")String type, @Param("geohash")String geohash, @Param("startPos")int startPos, @Param("pageSize")int pageSize);

    int updataShareByGivequan(@Param("businessId")Integer businessId);
}