package com.citytuike.mapper;

import com.citytuike.model.TpBusinessDiscount;
import com.citytuike.model.TpBusinessUseCash;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpBusinessDiscountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    int insert(TpBusinessDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    TpBusinessDiscount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessDiscount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_discount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessDiscount record);

    int getCountByBusinessId(@Param("business_id") Integer business_id);

    List<TpBusinessUseCash> selectByPageByBusinessId(@Param("business_id") Integer business_id, @Param("startPos") int startPos, @Param("pageSize") int pageSize);
}