package com.citytuike.mapper;

import com.citytuike.model.TpBusinessCashFace;

import java.util.List;

public interface TpBusinessCashFaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    int insert(TpBusinessCashFace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessCashFace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    TpBusinessCashFace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessCashFace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_cash_face
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessCashFace record);

    List<TpBusinessCashFace> findAllBusinessCashFace();
}