package com.citytuike.mapper;

import com.citytuike.model.TpBusinessTag;

public interface TpBusinessTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */
    TpBusinessTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessTag record);
}