package com.citytuike.mapper;

import com.citytuike.model.TpBusinessComment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpBusinessCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    int insert(TpBusinessComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    int insertSelective(TpBusinessComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    TpBusinessComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpBusinessComment record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_business_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpBusinessComment record);

    List<TpBusinessComment> findAllBusinessCommentByBusinessId(@Param("id") int id);
}