package com.citytuike.mapper;

import com.citytuike.model.TpChatGroupUser;
import org.apache.ibatis.annotations.Param;

public interface TpChatGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    int insert(TpChatGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    int insertSelective(TpChatGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    TpChatGroupUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpChatGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpChatGroupUser record);

    int updateChatGroupUserByStatus(@Param("group_id") String group_id, @Param("user_id") String user_id);
}