package com.citytuike.mapper;

import com.citytuike.model.TpChatLog;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpChatLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int insert(TpChatLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int insertSelective(TpChatLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    TpChatLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpChatLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TpChatLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpChatLog record);

    int getCount(@Param("room") String room);

    List<TpChatLog> selectByPage(@Param("room")String room, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}