package com.citytuike.mapper;

import com.citytuike.model.TpBusinessUseCash;
import com.citytuike.model.TpChatFriendList;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpChatFriendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    int insert(TpChatFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    int insertSelective(TpChatFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    TpChatFriendList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpChatFriendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_chat_friend_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpChatFriendList record);

    int getCount(@Param("im_id") String im_id);

    List<TpChatFriendList> selectByPage(@Param("im_id") String im_id, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}