package com.citytuike.mapper;

import com.citytuike.model.TpDevicePlay;
import org.apache.ibatis.annotations.Param;

public interface TpDevicePlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    int insert(TpDevicePlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    int insertSelective(TpDevicePlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    TpDevicePlay selectByPrimaryKey(Integer deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpDevicePlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_device_play
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpDevicePlay record);

    TpDevicePlay findDevicePlayByDeviceId(Integer device_id);

    int updataDeviceByRegionId(@Param("device_id") Integer device_id, @Param("district") Integer district);
}