package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumComment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpPhotoAlbumCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    TpPhotoAlbumComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumComment record);

    List<TpPhotoAlbumComment> findAllPhotoAlbumComment(@Param("p_id") String p_id);
}