package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumTmpClassify;

import java.util.List;

public interface TpPhotoAlbumTmpClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumTmpClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumTmpClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    TpPhotoAlbumTmpClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumTmpClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp_classify
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumTmpClassify record);

    List<TpPhotoAlbumTmpClassify> findAllClassify();
}