package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumUser;
import com.citytuike.model.TpUserFriendApply;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpPhotoAlbumUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    TpPhotoAlbumUser selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumUser record);

    int getCount(@Param("user_id") Integer user_id);

    List<TpUserFriendApply> selectByPage(@Param("user_id")Integer user_id, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}