package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumTmp;
import com.citytuike.model.TpUserFriendApply;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpPhotoAlbumTmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tmpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    TpPhotoAlbumTmp selectByPrimaryKey(Integer tmpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumTmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_tmp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumTmp record);

    int getCount(String c_id);

    List<TpUserFriendApply> selectByPage(@Param("c_id") String c_id, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}