package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumAd;

public interface TpPhotoAlbumAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    TpPhotoAlbumAd selectByPrimaryKey(Integer adId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumAd record);
}