package com.citytuike.mapper;

import com.citytuike.model.TpPhotoAlbumUserImage;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpPhotoAlbumUserImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    int insert(TpPhotoAlbumUserImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    int insertSelective(TpPhotoAlbumUserImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    TpPhotoAlbumUserImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpPhotoAlbumUserImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_photo_album_user_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpPhotoAlbumUserImage record);

    int deleteByPid(@Param("p_id") String p_id);

    List<TpPhotoAlbumUserImage> findAllPhotoAlbumUserImageByPid(@Param("p_id")Integer p_id);
}