package com.citytuike.mapper;

import com.citytuike.model.TpReplay;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpReplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int insert(TpReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int insertSelective(TpReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    TpReplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TpReplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_replay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpReplay record);

    List<TpReplay> findAllReplayByDynamicId(@Param("d_id") Integer d_id);
}