package com.citytuike.mapper;

import com.citytuike.model.TpChatLog;
import com.citytuike.model.TpUserFriendApply;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpUserFriendApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    int insert(TpUserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    int insertSelective(TpUserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    TpUserFriendApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpUserFriendApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friend_apply
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpUserFriendApply record);

    int getCount(@Param("user_id") Integer user_id);

    List<TpUserFriendApply> selectByPage(@Param("user_id")Integer user_id, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}