package com.citytuike.mapper;

import com.citytuike.model.TpUsersGoods;

public interface TpUsersGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int insert(TpUsersGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int insertSelective(TpUsersGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    TpUsersGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpUsersGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TpUsersGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_users_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpUsersGoods record);
}