package com.citytuike.mapper;

import com.citytuike.model.TpUserFriends;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpUserFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    int insert(TpUserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    int insertSelective(TpUserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    TpUserFriends selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TpUserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user_friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TpUserFriends record);

    int getCount(@Param("keyword")String keyword, @Param("user_id")Integer user_id);

    List<TpUserFriends> selectByPage(@Param("keyword")String keyword, @Param("user_id")Integer user_id, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
}